apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oleg-ecr-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 314525640319.dkr.ecr.il-central-1.amazonaws.com  # Must exactly match the registered repo URL
    chart: oleg/helm/nginx                                    # Path inside the Helm OCI registry
    targetRevision: 0.1.1
    helm:
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dep
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
