
labels:
  app: nginx
replicaCount: 3
name: nginx
namespace: nginx-dep
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
containerPort: 80
resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
volumeMounts: 
 - name: oleg-secret-volume
   mountPath: "/etc/secret"
   readOnly: true 
 - name: pvc-volume
   mountPath: "/mnt/data"
volumes: 
 - name: oleg-secret-volume
   secret:
    secretName: nginx-secret
 - name: pvc-volume
   persistentVolumeClaim:
    claimName: oleg-pvc
ingress:
  enabled: true
  className: nginx               # or your ingress controller’s class
  host: oleg-ingress-nginx
  annotations:                 
    kubernetes.io/ingress.class: nginx
  tls: false                    
  tlsSecret: '' 