apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-deployment.fullname" . }}-lb
  labels:
    {{- include "nginx-deployment.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "nginx-deployment.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
