apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}-lb
  labels:
{{ include "nginx.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  selector:
{{ include "nginx.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
